services:
  sentiment-analysis:
    build:
      context: ./sentiment-analysis
    ports:
      - "8001:8000"
    volumes:
      - sentiment-models:/app/models
    environment:
      - MODEL_NAME=${MODEL_NAME_QUANTIZED_SENTIMENT}
    deploy:
      resources:
        limits:
          memory: "1g"
          cpus: "0.5"
        reservations:
          memory: "512m"
          cpus: "0.25"
    container_name: sentiment-analysis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cerberus-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  summarization:
    build:
      context: ./summarization
    ports:
      - "8002:8000"
    volumes:
      - summarization-models:/app/models
    environment:
      - MODEL_NAME=${MODEL_NAME_QUANTIZED_SUMMARIZATION}
    deploy:
      resources:
        limits:
          memory: "2g"
          cpus: "1.0"
        reservations:
          memory: "1g"
          cpus: "0.5"
    container_name: summarization
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cerberus-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  text-generation:
    build:
      context: ./text-generation
    ports:
      - "8003:8000"
    volumes:
      - textgen-models:/app/models
    environment:
      - MODEL_NAME=${MODEL_NAME_QUANTIZED_TEXTGEN}
    deploy:
      resources:
        limits:
          memory: "3g"
          cpus: "2.0"
        reservations:
          memory: "2g"
          cpus: "1.0"
    container_name: text-generation
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cerberus-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  sentiment-models:
  summarization-models:
  textgen-models:

networks:
  cerberus-network:
    driver: bridge